POST http://localhost:4000/api/user/register
Content-Type: application/json

{
  "email": "johndoe@mail.com",
  "password": "!Johndoe123"
}

###

POST http://localhost:4000/api/user/login
Content-Type: application/json

{
  "email": "johndoe@mail.com",
  "password": "!Johndoe123"
}


###

GET http://localhost:4000/api/workout
Authorization: Bearer

###

GET http://localhost:4000/api/workout/te
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzBhM2IyOGQ5MGY3MTBkNjBiODgzOWQiLCJpYXQiOjE2NjE2NTgyODUsImV4cCI6MTY2MTkxNzQ4NX0.VBIVr7zRyDHmtSS9fhRB9mwjFhN8SK_QWRyAbEqRX84